server:
  port: 3282
spring:
  datasource:
    url: jdbc:h2:./db/sixdb;AUTO_SERVER=TRUE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:sql/schema-h2.sql
#      data-locations: classpath:sql/data-h2.sql
