CREATE TABLE IF NOT EXISTS APP_INFO
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    MSG          VARCHAR(50) NOT NULL COMMENT '信息',
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE APP_INFO IS '应用信息表';

CREATE TABLE IF NOT EXISTS UPLOAD_HISTORY
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '文件ID',
    FILE_URL      VARCHAR(100) NOT NULL COMMENT '文件URL',
    FILE_NAME     VARCHAR(100) DEFAULT NULL COMMENT '原始文件名',
    FILE_S3_URL   VARCHAR(100) DEFAULT NULL COMMENT 'S3类型URL',
    FILE_NEW_NAME VARCHAR(100) DEFAULT NULL COMMENT '新文件名',
    VENDOR        VARCHAR(30)  DEFAULT NULL COMMENT '服务厂商',
    BUCKET_NAME   VARCHAR(30)  DEFAULT NULL COMMENT '存储桶名称',
    FILE_PATH     VARCHAR(100) DEFAULT NULL COMMENT 'OSS中的路径+新文件名',
    FILE_SIZE     INT          DEFAULT 0 COMMENT '文件大小(KB)',
    MEDIA_TYPE    VARCHAR(30)  DEFAULT NULL COMMENT '文件类型',
    SUFFIX        VARCHAR(30)  DEFAULT NULL COMMENT '文件后缀名',
    CREATED_BY    VARCHAR(20)  DEFAULT 'SYS' COMMENT '上传人',
    CREATED_TIME  VARCHAR(50)  DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间'
);