CREATE TABLE IF NOT EXISTS APP_INFO
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    MSG          VARCHAR(50) NOT NULL COMMENT '信息',
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE APP_INFO IS '应用信息表';

CREATE TABLE IF NOT EXISTS UPLOAD_HISTORY
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '文件ID',
    FILE_URL     VARCHAR(100) NULL     DEFAULT NULL COMMENT '文件URL',
    FILE_NAME    VARCHAR(100) NULL     DEFAULT NULL COMMENT '文件名',
    FILE_S3_URL  VARCHAR(100) NULL     DEFAULT NULL COMMENT 'S3类型URL',
    FILE_PATH    VARCHAR(100) NULL     DEFAULT NULL COMMENT '路径',
    CREATED_BY   VARCHAR(20)  NOT NULL DEFAULT 'SYS' COMMENT '上传人',
    CREATED_TIME VARCHAR(50)  NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间'
);